# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b8f6f14cd5de718989f3e6ad97605c77f6168e005d33939d587b5a02273052719a5f3731038073e152cf1710bf83ba99df8b0c9e00a26155548f5eb02e372ce

test:
  secret_key_base: 2260c9c3f69a7e8b271976e10ea209d0044846dca4f0c04af1fe644105bee02851ac83ef5b2c6cc8a5a15521eb58df7180dd0e3abf966a61ba80bf47cf8ea57b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
